# Site settings
title: Perivan
url: http://178.62.13.11/perivan
# url: http://www.virtualboardroom.co.uk
description: >
  Virtualboardroom&reg; is a board portal which allows you to securely
  collaborate with others in the compilation of the board pack and then to
  share that and other key board information with directors. TODO

# Contact
email: info@virtualboardroom.co.uk # TODO
telephone: +44 (0)20 7562 2200
fax: +44 (0)20 7562 2203 # TODO
address1: 21 Worship Street
address2: London
address3: EC2A 2DW

# Navigation sections
nav-sections:
  - History
  - Management & Administration
  - Policies & The Environment

# Build settings
markdown: kramdown
permalink: /news/:title

exclude:
  - dev_serve.sh
  - Guardfile
  - Gemfile
  - Gemfile.lock
  - README.md

sass:
  style: :compressed
  sass_dir: _scss

gems:
  - jekyll-sitemap
